version: 0.2

phases:
  pre_build:
    commands:
      # 1. Buscamos la URL de la API usando el CLI de AWS. 
      # Filtramos por el nombre que le pusiste a tu HttpApi en la template.
      - echo Buscando la URL de la API...
      - API_ID=$(aws apigatewayv2 get-apis --query "Items[?Name=='upload-api'].ApiId" --output text)
      - REGION=$AWS_REGION
      - FULL_URL="https://${API_ID}.execute-api.${REGION}.amazonaws.com/upload-url"
      - echo "La URL detectada es $FULL_URL"

  build:
    commands:
      # 2. El comando mágico: 'sed' busca el marcador y lo cambia por la URL real
      - sed -i "s|REPLACE_ME_WITH_API_URL|$FULL_URL|g" index.html

  post_build:
    commands:
      # 3. Subimos el archivo ya modificado al bucket web
      - aws s3 cp index.html s3://web-bucket-html-${AWS::AccountId}/index.html
      # 4. (Opcional) Limpiamos la caché de CloudFront para que el cambio sea instantáneo
      - DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Origins.Items[0].Id=='web-bucket-origin'].Id" --output text)
      - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"

artifacts:
  files:
    - '**/*'