version: 0.2

phases:
  pre_build:
    commands:
      - echo "Detectando entorno..."
      # CodeBuild ya sabe su cuenta y región, no necesitas !Ref
      - ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - BUCKET_NAME="web-bucket-html-${ACCOUNT_ID}"
      - echo "Buscando la URL de la API..."
      # Buscamos la API por nombre
      - API_ID=$(aws apigatewayv2 get-apis --query "Items[?Name=='upload-api'].ApiId" --output text)
      - FULL_URL="https://${API_ID}.execute-api.${AWS_REGION}.amazonaws.com/upload-url"
      - echo "La URL detectada es ${FULL_URL}"

  build:
    commands:
      - echo "Inyectando URL en index.html..."
      - sed -i "s|REPLACE_ME_WITH_API_URL|${FULL_URL}|g" index.html

  post_build:
    commands:
      - echo "Subiendo archivo a S3..."
      - aws s3 cp index.html s3://${BUCKET_NAME}/index.html
      - echo "Limpiando caché de CloudFront..."
      # Buscamos la distribución que tiene como origen el nombre de tu bucket
      - DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Origins.Items[0].DomainName, '${BUCKET_NAME}')].Id" --output text)
      - if [ "$DIST_ID" != "None" ]; then aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"; fi

artifacts:
  files:
    - '**/*'