AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  UserEmail:
    Type: String
    Default: 'manugalang2007@gmail.com'
    Description: Your email for celebrity alerts.

Resources:
  # 1. THE WEBSITE HOSTING (S3)
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false

  WebsitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

  # 2. THE IMAGE UPLOAD BUCKET (With CORS)
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "celebrity-upload-${AWS::AccountId}"
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt ImageProcessQueue.Arn
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [PUT, POST]
            AllowedOrigins: ['*']

  # 3. DYNAMODB TABLE (Standard Version)
  CelebrityResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ImageKey
          AttributeType: S
      KeySchema:
        - AttributeName: ImageKey
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # 4. SNS NOTIFICATION
  CelebrityAlertTopic:
    Type: AWS::SNS::Topic

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref CelebrityAlertTopic
      Protocol: email
      Endpoint: !Ref UserEmail

  # 5. LAMBDA EXECUTION ROLE
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CelebrityProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rekognition:RecognizeCelebrities
                  - s3:GetObject
                  - dynamodb:PutItem
                  - sns:Publish
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: "*"

  # 6. THE PROCESSING LAMBDA (Rekognition + SNS)
  ProcessingLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref CelebrityResultsTable
          SNS_TOPIC_ARN: !Ref CelebrityAlertTopic
      Policies:
        - AmazonRekognitionFullAccess
        - AmazonS3ReadOnlyAccess
        - DynamoDBCrudPolicy: {TableName: !Ref CelebrityResultsTable}
        - SNSPublishMessagePolicy: {TopicName: !GetAtt CelebrityAlertTopic.TopicName}
      Events:
        QueueEvent:
          Type: SQS
          Properties:
            QueueArn: !GetAtt ImageProcessQueue.Arn
      Code:
        ZipFile: |
          import boto3
          import os
          import json
          import urllib.parse
          import logging

          # Set up logging for CloudWatch
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          # Initialize clients outside the handler for better performance
          rekognition = boto3.client('rekognition')
          dynamodb = boto3.resource('dynamodb')
          sns = boto3.client('sns')

          def handler(event, context):
            table = dynamodb.Table(os.environ['TABLE_NAME'])
            sns_topic = os.environ['SNS_TOPIC_ARN']
            
            logger.info(f"Received event: {json.dumps(event)}")
            
            for record in event['Records']:
                try:
                    # 1. SQS wraps the S3 event in a string called 'body'
                    s3_event = json.loads(record['body'])
                    
                    # Skip if it's a test event or doesn't contain 'Records'
                    if 'Records' not in s3_event:
                        continue
                        
                    for s3_rec in s3_event['Records']:
                        # 2. Extract Bucket and Key (unquote handles special chars in filename)
                        bucket = s3_rec['s3']['bucket']['name']
                        raw_key = s3_rec['s3']['object']['key']
                        key = urllib.parse.unquote_plus(raw_key)
                        
                        logger.info(f"Processing file: {key} from bucket: {bucket}")
                        
                        # 3. Call Amazon Rekognition
                        response = rekognition.recognize_celebrities(
                            Image={'S3Object': {'Bucket': bucket, 'Name': key}}
                        )
                        
                        # 4. Parse Results
                        celebs = response.get('CelebrityFaces', [])
                        unrecognized = response.get('UnrecognizedFaces', [])
                        
                        if celebs:
                            celeb = celebs[0] # Get the most prominent celebrity
                            celeb_name = celeb.get('Name', 'Unknown')
                            confidence = str(celeb.get('MatchConfidence', 0))
                            urls = celeb.get('Urls', [])
                            id_val = celeb.get('Id', 'N/A')
                        else:
                            celeb_name = "No Celebrity Detected"
                            confidence = "0"
                            urls = []
                        
                        # 5. Save to DynamoDB
                        table.put_item(
                            Item={
                                'ImageKey': key,
                                'CelebrityName': celeb_name,
                                'Confidence': confidence,
                                'Bucket': bucket,
                                'FaceCount': len(celebs) + len(unrecognized)
                            }
                        )
                        
                        # 6. Send SNS Alert
                        notification_msg = (
                            f"Celebrity Detection Results:\n"
                            f"----------------------------\n"
                            f"File: {key}\n"
                            f"Detected: {celeb_name}\n"
                            f"Confidence: {confidence}%\n"
                            f"More Info: {urls[0] if urls else 'None'}"
                        )
                        
                        sns.publish(
                            TopicArn=sns_topic,
                            Message=notification_msg,
                            Subject=f"Celebrity Alert: {celeb_name}"
                        )
                        
                except Exception as e:
                    logger.error(f"Error processing record: {str(e)}")
                    # In a production environment, you might want to re-raise this 
                    # so the message goes to a Dead Letter Queue (DLQ)
                    continue

            return {"status": "success", "processed_count": len(event['Records'])}}

  # 7. SQS QUEUE & PERMISSION
  ImageProcessQueue:
    Type: AWS::SQS::Queue

  LambdaSQSEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt ImageProcessQueue.Arn
      FunctionName: !Ref ProcessingLambda

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [!Ref ImageProcessQueue]
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: {Service: s3.amazonaws.com}
            Action: sqs:SendMessage
            Resource: !GetAtt ImageProcessQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::celebrity-upload-${AWS::AccountId}"